import Footer from '@/components/footer/page'
import '../style/footer.css'
import '../style/globals.css'

import { Cinzel_Decorative } from "next/font/google";
import { Lato } from 'next/font/google';
const lato=Lato(
  {
    weight:'400',
    variable:'--lato',
    subsets:['latin']
  }
)
const cinzel=Cinzel_Decorative({
  weight:'700',
  variable:'--cinzel',
  subsets:['latin'],
  
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cinzel.className} ${lato.className}`}>
      <body className={lato.className}>{children}
      <Footer/></body>
    </html>
  )
}
